#!/bin/bash

MODULES=`cd source ; find -name '*.d'`

SRC_DIR="source"
WORK_DIR="tmp"
BUILD_DIR="$WORK_DIR/docs"

COMMON_OPTS="-de -I$SRC_DIR -od$BUILD_DIR/obj -w"
DDOC_OPTS="-c -o- -D -Dd$BUILD_DIR viola.ddoc"

for m in $MODULES
do
    dmd $COMMON_OPTS $DDOC_OPTS $SRC_DIR/$m
done
